# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x05\x63loud\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xf2\x01\n\nCalculator\x12,\n\x03\x41\x64\x64\x12\x11.cloud.AddRequest\x1a\x12.cloud.AddResponse\x12,\n\x03Sub\x12\x11.cloud.AddRequest\x1a\x12.cloud.AddResponse\x12,\n\x03Mul\x12\x11.cloud.AddRequest\x1a\x12.cloud.AddResponse\x12,\n\x03\x44iv\x12\x11.cloud.AddRequest\x1a\x12.cloud.AddResponse\x12,\n\x03Mod\x12\x11.cloud.AddRequest\x1a\x12.cloud.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=27
  _globals['_ADDREQUEST']._serialized_end=67
  _globals['_ADDRESPONSE']._serialized_start=69
  _globals['_ADDRESPONSE']._serialized_end=98
  _globals['_CALCULATOR']._serialized_start=101
  _globals['_CALCULATOR']._serialized_end=343
# @@protoc_insertion_point(module_scope)
